name: CI/CD
on:
  push:
    branches:
      - main
      - develop
      - feat/**
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - main
      - develop
      - release/current

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy ODOO to EC2
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feat/')
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ^24.12.0
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: CDK Deploy
        env:
          ODOO_DB_PASSWORD: ${{ secrets.ODOO_DB_PASSWORD }}
          CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: |
          npx cdk deploy --require-approval never \
            --parameters OdooDbPassword=${{ secrets.ODOO_DB_PASSWORD }} \
            --parameters OdooAdminPassword=${{ secrets.ODOO_ADMIN_PASSWORD }}
          
            